export let TRIPS = [
  {
    id: 1,
    name: "Jainism",
    book: " Kalpa Sūtras",
    price_adult: 60,
    price_child: 30,
    time: "12",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/img/banner/jainism.png  ",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Rio de Janeiro, Brazil",
    images: [
      " ",
      "assets/img/trip/thumb/trip_6.jpg",
      "assets/img/trip/thumb/trip_7.jpg",
      "assets/img/trip/thumb/trip_8.jpg",
    ],
    highlights: [
      "Numerous kiosks",
      "First in a string of Atlantic Ocean-facing beaches",
      "Sand is flanked by mountains in the background",
      "Swing in the turquoise waters",
      "Water Sports",
    ]
  },
   
  {
    id: 2,
    name: "Swami Narayan",
    book: "Shikhapatri",
    price_adult: 90,
    price_child: 45,
    time: "4",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/img/banner/swaminarayanism.png",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Rio de Janeiro, Brazil",
    images: [],
    highlights: []
  },
  {
    id: 3,
    name: "Hinduism",
    book: " Bhagavad Gita",
    price_adult: 30,
    price_child: 15,
    time: "6",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/img/banner/hinduism.png",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "São Paulo, Brazil",
    images: [],
    highlights: []
  },
  {
    id: 4,
    name: "Buddhism",
    book: " Tripitaka",
    price_adult: 500,
    price_child: 250,
    time: "24",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/img/banner/buddhisam.png",
    description: "From sexy Ipanema and Copacabana, to more secluded and slightly lesser-known stretches of sand, like Prainha Beach, Brazil's Rio de Janeiro is best known for its beaches. Grab your sunscreen and Brazilian bikinis and head to the sunny shores of Rio's best beaches.",
    location: "Fernando de Noronha, Brazil",
    images: [],
    highlights: []
  }
]
